
train: C:\projectyolo\data\train
val: C:\projectyolo\data\val
# test: C:\projectyolo\data\test\images

names:
  0: G_ML_NUM
  1: UNIT
  2: HEAT
  3: PORTEIN
  4: TOTALFAT
  5: SATFAT
  6: TRANSFAT
  7: CARBOHYDRATE
  8: SUGAR
  9: SODIUM